# Usar la imagen base de nginx
FROM nginx:latest

# Copiar el archivo de configuración personalizado de NGINX al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para el tráfico HTTP
EXPOSE 80