FROM node:16

WORKDIR /app

# Copia package.json y package-lock.json
COPY package.json .
COPY package-lock.json .

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Reinstala bcrypt dentro del contenedor
RUN npm rebuild bcrypt --build-from-source

# Comando para iniciar la aplicación
CMD ["npm", "start"]